<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <!-- 确保程序集名称唯一 -->
    <AssemblyName>康鹤多旋翼无人机检修平台</AssemblyName>
    <RootNamespace>DroneSimulator</RootNamespace>
    <!-- 添加应用程序图标 -->
    <ApplicationIcon>Resources\shortcut_icon.ico</ApplicationIcon>
    <Title>康鹤多旋翼无人机检修平台</Title>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ArduPilot.Core\**" />
    <EmbeddedResource Remove="ArduPilot.Core\**" />
    <None Remove="ArduPilot.Core\**" />
    <Page Remove="ArduPilot.Core\**" />
  </ItemGroup>
	
  <ItemGroup>
	<Resource Include="Resources\shortcut_icon.ico" />
  </ItemGroup>  

  <ItemGroup>
    <Resource Include="Resources\Image1.png" />
    <Resource Include="Resources\Image2.png" />
    
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IO.Ports" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
	<Resource Include="Resources\Image3.png" />
    <Resource Include="Resources\Image4.png" />
    <Resource Include="Resources\Image5.png" />	
    <Resource Include="Resources\aerospace-bg.jpg" />
    <Resource Include="Resources\drone-icon-0.png" />
    <Resource Include="Resources\drone-icon.png" />
    <Resource Include="Resources\logo.png" />
    <Resource Include="Resources\扩展-飞控-电源.jpg" />
    <Resource Include="Resources\飞控-电调-电机.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
